name: Daily WooCommerce Export

on:
  schedule:
    - cron: '0 23 * * *'  # UTC 23:00 (HKT 07:00 次日)
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials file
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: echo "$GCP_SA_JSON" > /tmp/credentials.json

      - name: Debug step - Check file existence
        run: |
          echo "檢查當前目錄檔案："
          ls -la
          echo "檢查 /tmp/credentials.json 是否存在："
          ls -la /tmp/credentials.json || echo "檔案不存在"

      - name: Debug step - Print simple message
        run: echo "工作流程正常執行到此步驟"

      - name: Debug step - Check Python version and script content
        run: |
          python --version
          echo "顯示 archive_orders.py 內容："
          cat archive_orders.py
          echo "檢查腳本是否可執行："
          python -m py_compile archive_orders.py || echo "腳本語法錯誤"

      - name: Debug step - Before running archive orders script
        run: echo "準備執行 archive_orders.py"

      - name: Run archive orders script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: python archive_orders.py

      - name: Run Woo Orders export script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: python script1.py
