name: Daily Updates
on:
  schedule:
    - cron: '0 1 * * *' # 每天香港時間上午9點 (UTC+8 -> UTC 1:00)
  workflow_dispatch:

jobs:
  update_orders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread oauth2client gspread-formatting pytz
      - name: Run archive_orders.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json
          python archive_orders.py
      - name: Run script1.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json
          python script1.py
      - name: Run availability.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json
          python availability.py
