name: Daily WooCommerce Export

on:
  schedule:
    - cron: '0 23 * * *'  # 每天早上 7:00 (HKT, UTC 23:00)
    - cron: '0 19 * * *'  # 每天凌晨 3:00 (HKT, UTC 19:00)
    - cron: '0 4 * * *'   # 每天中午 12:00 (HKT, UTC 4:00)
    - cron: '0 7 * * *'   # 每天下午 3:00 (HKT, UTC 7:00)
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check GOOGLE_CREDENTIALS
        run: |
          if [ -z "$GOOGLE_CREDENTIALS" ]; then
            echo "錯誤：GOOGLE_CREDENTIALS 環境變數為空"
            exit 1
          else
            echo "GOOGLE_CREDENTIALS 已設置"
          fi
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Write credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json

      - name: Run availability script
        if: github.event.schedule == '0 23 * * *'  # 僅在 7:00 AM 運行
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python availability.py

      - name: Run archive orders script
        if: github.event.schedule == '0 23 * * *' || github.event.schedule == '0 4 * * *' || github.event.schedule == '0 7 * * *'  # 在 7:00 AM, 12:00 PM, 3:00 PM 運行
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python archive_orders.py

      - name: Run Woo Orders export script
        if: github.event.schedule == '0 23 * * *'  # 僅在 7:00 AM 運行
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python script1.py

      - name: Run Tour Orders export script
        if: github.event.schedule == '0 23 * * *'  # 僅在 7:00 AM 運行
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python tour.py

      - name: Run Rescheduled Orders export script
        if: github.event.schedule == '0 23 * * *'  # 僅在 7:00 AM 運行
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          WC_SITE: "https://kayarine.club/wp-json/wc/v3/orders"
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python rescheduled.py

      - name: Run Update Arrival Status script
        if: github.event.schedule == '0 19 * * *'  # 僅在 3:00 AM 運行
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python update_arrival_status.py
